### obtener items
GET http://localhost:3000/api/items

### crear item
POST http://localhost:3000/api/items
Content-Type: application/json

{
  "estado": "en carrito",
  "cantidad": 1,
  "mueble": 1
}

### crear otro item
POST http://localhost:3000/api/items
Content-Type: application/json

{
  "estado": "pendiente",
  "cantidad": 2,
  "mueble": 3
}

### otro mas
POST http://localhost:3000/api/items
Content-Type: application/json

{
  "estado": "en proceso",
  "cantidad": 3,
  "mueble": 4
}

### aumentar cantidad del item 1 en 3 unidades 75000 * 4
PATCH http://localhost:3000/api/items/1
Content-Type: application/json

{
  "cantidad": 4
}

### item completado
POST http://localhost:3000/api/items
Content-Type: application/json

{
  "estado": "completado",
  "cantidad": 5,
  "mueble": 2,
  "pedido": 1
}

### item cancelado
POST http://localhost:3000/api/items
Content-Type: application/json

{
  "estado": "cancelado",
  "cantidad": 2,
  "mueble": 5,
  "pedido": 1
}
