### obtener todos los clientes
GET http://localhost:3000/api/clientes

### POST a character
# @name createCliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "direccion": "Calle Falsa 340",
  "telefono": "123456789",
  "dni": "34567890",
  "usuario": "juanperez",
  "email": "juanmail@gmail.com",
  "contrasenia": "contrasenia4u54",
  "pedidos": [],
  "fondos": 1000,
  "puntos": 100,
  "favoritos": []
  }

### ID
@id = {{createCliente.response.body.data.id}}

### GET one client
GET http://localhost:3000/api/clientes/{{id}}

### modificar un cliente (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/clientes/{{id}}
Content-Type: application/json

{
  "nombre": "Quispe",
  "apellido": "Mamani",
  "direccion": "Cerro Falso 200",
  "telefono": "783456789",
  "dni": "20456789",
  "usuario": "quispemamani",
  "email": "left4quispe@gmail.com",
  "contrasenia": "cerveza454",
  "pedidos": [],
  "fondos": 0,
  "puntos": 0,
  "favoritos": []
  }

### POST a cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Bruno",
    "apellido": "Bassi",
    "direccion": "Lima 123",
    "telefono": "5123456789",
    "dni": "372712345",
    "usuario": "brunobassinoziglia",
    "email": "megamanbassi@gmail.com",
    "contrasenia": "ohcielos123",
    "pedidos": [],
    "fondos": 2000,
    "puntos": 500,
    "favoritos": []
}

### POST a client to delete
# @name createClientToDelete
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Pato",
    "apellido": "the hedhehog",
    "direccion": "Callao 1300",
    "telefono": "54123456789",
    "dni": "477123456",
    "usuario": "patothehedhehog",
    "email": "patothehedhog@hotmail.com",
    "contrasenia": "patito123",
    "pedidos": [],
    "fondos": 2000,
    "puntos": 500,
    "favoritos": []
}

#### ID to delete
@idToDelete = {{createClientToDelete.response.body.data.id}}

### modificar un cliente (PATCH - recurso parcial y no idempotente)
PATCH http://localhost:3000/api/clientes/{{id}}
Content-Type: application/json

{
  "nombre": "Julian",
  "apellido": "Omar Maruca",
  "usuario": "july3p",
  "email": "july3p@gmail.com"
}

### PATCH a cliente
PATCH http://localhost:3000/api/clientes/{{idToDelete}}
Content-Type: application/json

{
  "puntos": 10000
}

### DELETE a client
DELETE http://localhost:3000/api/clientes/{{idToDelete}}
