### obtener todos los clientes
GET http://localhost:3000/api/clientes

### crear cliente administrador
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Administrador",
    "apellido": "General",
    "direccion": "Calle Central 100",
    "telefono": "1122334455",
    "dni": "273456789",
    "usuario": "admin",
    "email": "admin@muebleria.com",
    "contrasenia": "123", 
    "rol": "admin",
    "fondos": 100000 
}

### POST a character
# @name createCliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Luffy",
    "apellido": "Monkey D.",
    "direccion": "East Blue 01",
    "telefono": "1189001122",
    "dni": "370112238",
    "usuario": "luffy",
    "email": "luffy@onepiece.jp",
    "contrasenia": "gomuGomu",
    "fondos": 2100
}

### POST a character
# @name clienteToDelete
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Goku",
    "apellido": "Son",
    "direccion": "Monte Paoz 77",
    "telefono": "1122334455",
    "dni": "301253456",
    "usuario": "gokuson",
    "email": "goku@kamehouse.com",
    "contrasenia": "kamehameha123",
    "fondos": 1500
}

### varios clientes, separados
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Vegeta",
    "apellido": "Saiyan",
    "direccion": "Calle Capsule 12",
    "telefono": "1165432109",
    "dni": "321409876",
    "usuario": "vegeta_saiyan",
    "email": "vegeta@capsulecorp.jp",
    "contrasenia": "princeofall",
    "fondos": 1800
}

### POST a character
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nombre": "Bulma",
  "apellido": "Brief",
  "direccion": "Av. Capsule 01",
  "telefono": "1134567890",
  "dni": "289010123",
  "usuario": "bulmabrief",
  "email": "bulma@capsulecorp.jp",
  "contrasenia": "genius123",
  "fondos": 3200
}

### obtener favoritos del cliente
GET http://localhost:3000/api/clientes/2/favoritos

### obtener favoritos del cliente 2
GET http://localhost:3000/api/clientes/3/favoritos

### crear favorito para el cliente 2
POST http://localhost:3000/api/clientes/2/favoritos
Content-Type: application/json

{
  "muebleId": 1
}

### crear otro favorito para el cliente 2
POST http://localhost:3000/api/clientes/2/favoritos
Content-Type: application/json

{
  "muebleId": 4
}

### crear favorito para el cliente 3
POST http://localhost:3000/api/clientes/3/favoritos
Content-Type: application/json

{
  "muebleId": 2
}

### un favorito para cliente 1
GET http://localhost:3000/api/clientes/2/favoritos/mueble/1

### borrar favorito
DELETE http://localhost:3000/api/clientes/2/favoritos/1

### conseguir todos los pedidos de un cliente
GET http://localhost:3000/api/clientes/2/pedidos

### crear pedido
POST http://localhost:3000/api/clientes/2/pedidos
Content-Type: application/json

{
"items": [1,2],
"descuentos": [1]
}

### POST a character
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nombre": "Zoro",
  "apellido": "Roronoa",
  "direccion": "East Blue 02",
  "telefono": "1189003344",
  "dni": "37033445",
  "usuario": "zorororonoa",
  "email": "zoro@onepiece.jp",
  "contrasenia": "santoryu",
  "fondos": 1800
}

### ID
@id = {{createCliente.response.body.data.id}}

### GET one client
GET http://localhost:3000/api/clientes/{{id}}

### modificar un cliente (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/clientes/{{id}}
Content-Type: application/json

{
    "nombre": "Luffy",
    "apellido": "Monkey D.",
    "direccion": "Elbaph 99",
    "telefono": "1189001122",
    "dni": "370112239",
    "usuario": "luffy",
    "email": "luffy@onepiece.jp",
    "contrasenia": "gear5haoshoku",
    "fondos": 2100
}

### modificar un cliente (PATCH - recurso parcial y no idempotente)
PATCH  http://localhost:3000/api/clientes/{{id}}
Content-Type: application/json

{
  "usuario": "luffychad",
  "email": "luffychad@onepiece.jp"
}

### set id to delete
@idToDelete = {{clienteToDelete.response.body.data.id}}

### DELETE a character
DELETE http://localhost:3000/api/clientes/{{idToDelete}}
Content-Type: application/json
