GET http://localhost:3000/api/pedidos/2

POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
  "cliente": 2,
  "items": [
    {
      "mueble": 1,
      "cantidad": 1
    },
    {
      "mueble": 2,
      "cantidad": 1
    }
  ],
  "descuentos": 1
}
